version: '2'
services:
  spark-master:
    image: bde2020/spark-master:2.4.1-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - ENABLE_INIT_DAEMON=false
    volumes:
      - /data/spark:/data/spark
  spark-worker-1:
    image: bde2020/spark-worker:2.4.1-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    environment:
      - ENABLE_INIT_DAEMON=false
    volumes:
      - /data/spark:/data/spark
  spark-app:
    image: spark-digest
    container_name: spark-app
    depends_on:
      - spark-master
    volumes:
      - /data/spark:/data/spark
    environment:
      - SPARK_MASTER_NAME=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_APPLICATION_ARGS="zookeeper:2181 carloc sparkDigestGroup"